In [1]:
import pandas as pd

df = pd.read_csv('./Life.csv')
df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.25921,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2949,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2950,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.3511552,12633897.0,9.8,9.9,0.418,9.5
2951,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.34834,125525.0,1.2,1.3,0.427,10.0
2952,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2953,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.3588785,12222251.0,11.0,11.2,0.434,9.8

In [2]:
geo_df = pd.read_csv('./위도경도.csv')
geo_df

                        NAME   latitude   longitude
0                  Indonesia  -2.222961  117.270433
1                   Malaysia   3.792393  109.698868
2                      Chile -37.743607  -71.364375
3                    Bolivia -16.706877  -64.684754
4                       Peru  -9.154388  -74.378065
..                       ...        ...         ...
253                    Macao  22.157784  113.550198
254  Ashmore and Cartier Is. -12.432577  123.586368
255          Bajo Nuevo Bank  15.795010  -79.987866
256          Serranilla Bank  15.864461  -78.638119
257         Scarborough Reef  15.152113  117.753812

[258 rows x 3 columns]

In [3]:
# Country와 NAME이 같은 경우에 df2의 컬럼 추가
merged_df = pd.merge(df, geo_df, left_on='Country', right_on='NAME', how='left')

merged_df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,NAME,latitude,longitude
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,0.1,584.25921,33736494.0,17.2,17.3,0.479,10.1,Afghanistan,33.836267,66.008448
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,Afghanistan,33.836267,66.008448
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,Afghanistan,33.836267,66.008448
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,0.1,669.959,3696958.0,17.9,18.0,0.463,9.8,Afghanistan,33.836267,66.008448
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,Afghanistan,33.836267,66.008448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2949,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2,Zimbabwe,-19.002537,29.851885
2950,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,36.7,453.3511552,12633897.0,9.8,9.9,0.418,9.5,Zimbabwe,-19.002537,29.851885
2951,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,39.8,57.34834,125525.0,1.2,1.3,0.427,10.0,Zimbabwe,-19.002537,29.851885
2952,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8,Zimbabwe,-19.002537,29.851885
2953,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,43.5,547.3588785,12222251.0,11.0,11.2,0.434,9.8,Zimbabwe,-19.002537,29.851885

In [4]:
merged_df.to_csv('위도경도추가.csv', index=False)